apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    k8s-app: vault
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "vault"
spec:
  type: ClusterIP
  ports:
    - port: 8200
      protocol: TCP
      targetPort: 8200
  selector:
    k8s-app: vault
---
apiVersion: v1
kind: Service
metadata:
  name: vaultcluster
  labels:
    k8s-app: vaultcluster
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "vaultcluster"
spec:
  type: ClusterIP
  ports:
    - port: 8201
      protocol: TCP
      targetPort: 8201
  selector:
    k8s-app: vault
