# Default values for vault.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
prehook:
  repository: asia.gcr.io/company_dev
  prefix: vaultcert
  tag: 0.0.1
init:
  repository: asia.gcr.io/company_dev
  prefix: vaultinit
  tag: 0.0.6
image:
  repository: vault
  tag: 1.1.0
  pullPolicy: IfNotPresent
ingress:
  enabled: false
resources:
   limits:
    cpu: 500m
    memory: 1560Mi
   requests:
    cpu: 100m
    memory: 128Mi
service:
  type: ClusterIP
  port: 8200
readiness:
    readyIfSealed: false
    readyIfStandby: true
    readyIfUninitialized: true
configs:
  project_id: company-dev
